apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  minReadySeconds: 0
  selector:
    matchLabels:
      app: cron
  template:
    metadata:
      labels:
        app: cron
    spec:
      containers:
      - name: cron
        image: favish/cron-drupal:1.0.0-alpha.1
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: customcron
          mountPath: "/customcron"
          subPath: "customcron"
      volumes:
        - name: customcron
          configMap:
            name: cron

